/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SystemConfigRouteImport } from './routes/system-config'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconWorkflowsRouteImport } from './routes/recon-workflows'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DatabaseConnectionsRouteImport } from './routes/database-connections'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemConfigRoute = SystemConfigRouteImport.update({
  id: '/system-config',
  path: '/system-config',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconWorkflowsRoute = ReconWorkflowsRouteImport.update({
  id: '/recon-workflows',
  path: '/recon-workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseConnectionsRoute = DatabaseConnectionsRouteImport.update({
  id: '/database-connections',
  path: '/database-connections',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/cases': typeof CasesRoute
  '/data-sources': typeof DataSourcesRoute
  '/database-connections': typeof DatabaseConnectionsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/pipelines': typeof PipelinesRoute
  '/profile': typeof ProfileRoute
  '/recon-workflows': typeof ReconWorkflowsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/system-config': typeof SystemConfigRoute
  '/users': typeof UsersRoute
  '/workbench': typeof WorkbenchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/cases': typeof CasesRoute
  '/data-sources': typeof DataSourcesRoute
  '/database-connections': typeof DatabaseConnectionsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/pipelines': typeof PipelinesRoute
  '/profile': typeof ProfileRoute
  '/recon-workflows': typeof ReconWorkflowsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/system-config': typeof SystemConfigRoute
  '/users': typeof UsersRoute
  '/workbench': typeof WorkbenchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/cases': typeof CasesRoute
  '/data-sources': typeof DataSourcesRoute
  '/database-connections': typeof DatabaseConnectionsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/pipelines': typeof PipelinesRoute
  '/profile': typeof ProfileRoute
  '/recon-workflows': typeof ReconWorkflowsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/system-config': typeof SystemConfigRoute
  '/users': typeof UsersRoute
  '/workbench': typeof WorkbenchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/audit-logs'
    | '/cases'
    | '/data-sources'
    | '/database-connections'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/monitoring'
    | '/pipelines'
    | '/profile'
    | '/recon-workflows'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/system-config'
    | '/users'
    | '/workbench'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/audit-logs'
    | '/cases'
    | '/data-sources'
    | '/database-connections'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/monitoring'
    | '/pipelines'
    | '/profile'
    | '/recon-workflows'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/system-config'
    | '/users'
    | '/workbench'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/audit-logs'
    | '/cases'
    | '/data-sources'
    | '/database-connections'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/monitoring'
    | '/pipelines'
    | '/profile'
    | '/recon-workflows'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/system-config'
    | '/users'
    | '/workbench'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CasesRoute: typeof CasesRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DatabaseConnectionsRoute: typeof DatabaseConnectionsRoute
  DownloadsRoute: typeof DownloadsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  PipelinesRoute: typeof PipelinesRoute
  ProfileRoute: typeof ProfileRoute
  ReconWorkflowsRoute: typeof ReconWorkflowsRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SystemConfigRoute: typeof SystemConfigRoute
  UsersRoute: typeof UsersRoute
  WorkbenchRoute: typeof WorkbenchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-config': {
      id: '/system-config'
      path: '/system-config'
      fullPath: '/system-config'
      preLoaderRoute: typeof SystemConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recon-workflows': {
      id: '/recon-workflows'
      path: '/recon-workflows'
      fullPath: '/recon-workflows'
      preLoaderRoute: typeof ReconWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database-connections': {
      id: '/database-connections'
      path: '/database-connections'
      fullPath: '/database-connections'
      preLoaderRoute: typeof DatabaseConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AuditLogsRoute: AuditLogsRoute,
  CasesRoute: CasesRoute,
  DataSourcesRoute: DataSourcesRoute,
  DatabaseConnectionsRoute: DatabaseConnectionsRoute,
  DownloadsRoute: DownloadsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  PipelinesRoute: PipelinesRoute,
  ProfileRoute: ProfileRoute,
  ReconWorkflowsRoute: ReconWorkflowsRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SystemConfigRoute: SystemConfigRoute,
  UsersRoute: UsersRoute,
  WorkbenchRoute: WorkbenchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
